### ISSUE TITLE
test {modules,crates,structs} fails on master

### ISSUE THREAD

**Issue by hjr3** [steveklabnik/rustdoc#114]
On 13e5eda9bb2827f300b51fe1cf807af523d0c831 I am seeing the following tests fail:

```bash
$ cargo test --test source
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/source-2bf1e8ccf28f1c64

running 6 tests
test source_tests::pointer_syntax ... ok
test source_tests::run_test ... ok
test source_tests::parse_test ... ok
test crates ... FAILED
test modules ... FAILED
test structs ... FAILED

failures:

---- crates stdout ----
	crate_name = crates, roots = []
error: Crate not found: "crates"
thread 'crates' panicked at 'explicit panic', /Users/herman/projects/rustdoc/target/debug/build/rustdoc-3b5bfa564a211cec/out/source_generated.rs:1:576
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- modules stdout ----
	crate_name = modules, roots = []
error: Crate not found: "modules"
thread 'modules' panicked at 'explicit panic', /Users/herman/projects/rustdoc/target/debug/build/rustdoc-3b5bfa564a211cec/out/source_generated.rs:1:1171

---- structs stdout ----
	crate_name = structs, roots = []
error: Crate not found: "structs"
thread 'structs' panicked at 'explicit panic', /Users/herman/projects/rustdoc/target/debug/build/rustdoc-3b5bfa564a211cec/out/source_generated.rs:1:1766


failures:
    crates
    modules
    structs

test result: FAILED. 3 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test source'
```

It looks like travis is seeing the same thing here: https://travis-ci.org/steveklabnik/rustdoc/jobs/261029045

**Comment by steveklabnik** [comment]
This is passing for me locally :/

**Comment by mgattozzi** [comment]
Same. @steveklabnik I wonder if we have something on our machines that's letting it pass but others might not.

**Comment by steveklabnik** [comment]
The plot thickens: I ran `rustup update` and now it fails.

**Comment by steveklabnik** [comment]
Random shot in the dark, https://github.com/rust-lang/rust/pull/43611 was merged. hrm

**Comment by euclio** [comment]
Maybe we need to update the rls-analysis crate? I think an upgrade is blocked by https://github.com/nrc/rls-analysis/issues/81, though.

**Comment by steveklabnik** [comment]
@euclio it's like you read my mind
